version: '3'

services:
  mysql_db_service:
    build:
      context: ./MySQL
      dockerfile: Dockerfile
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: mainpassword
    command: --default-authentication-plugin=mysql_native_password
  upload_video:
    build: ./videoupload
    ports:
      - "3008:3000"
    depends_on:
      - authentication_service
      - file_system_service
      - mysql_db_service
    restart: always

  video_streaming:
    build: ./videostreaming
    ports:
      - "3007:3000"
    depends_on:
      - authentication_service
      - file_system_service
      - mysql_db_service
    restart: always

  authentication_service:
    build: ./authentication
    ports:
      - "3011:3000"
    depends_on:
      - mysql_db_service
    restart: always

  file_system_service:
    build: ./filesystemservice
    ports:
      - "3010:3000"
    depends_on:
      - authentication_service
      - mysql_db_service
    restart: always

  my_sql_service:
    build: ./my_sql_service
    ports:
      - "3012:3000"
    depends_on:
      - authentication_service
      - mysql_db_service
    restart: always

